Parameters:
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  DatabaseName:
    Type: String
  SecurityGroup:
    Type: String
  DatabaseUser:
    Type: String
    Default: dbuser
  DatabasePassword:
    Type: String
    Default: ChangeMe


Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet for Database
      DBSubnetGroupName: !Sub "${AWS::StackName}-db-subnet-group"
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
  Database:
    Type: AWS::RDS::DBCluster
    Properties:
      # Console says Serverless v1 maxed at 11.13
      # aws rds describe-db-engine-versions --engine aurora-postgresql --query "DBEngineVersions[].EngineVersion" -- highest is 14.3
      Engine: aurora-postgresql
      EngineMode: serverless             # only v1 at this time
      EngineVersion: 11.13
      DatabaseName:        !Ref DatabaseName
      DBClusterIdentifier: !Ref DatabaseName # default nested stack name is > 63 char PostgreSQL limit
      DBSubnetGroupName:   !Ref DBSubnetGroup
      MasterUsername:      !Ref DatabaseUser
      MasterUserPassword:  !Ref DatabasePassword
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  Host:
    Value: !GetAtt Database.Endpoint.Address
  Port:
    Value: !GetAtt Database.Endpoint.Port
  Name:
    Value: !Ref    DatabaseName       # CF has no output for the DatabaseName
  DatabaseUser:
    Value: !Ref    DatabaseUser
  DatabasePassword:
    Value: !Ref    DatabasePassword    
