Parameters:
  DatabaseName:
    Type: String
  DatabaseUser:
    Type: String
    Default: dbuser
  DatabasePassword:
    Type: String
    Default: ChangeMe
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  SecurityGroup:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet for Database
      DBSubnetGroupName: !Sub "${AWS::StackName}-db-subnet-group"
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
  Database:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineMode: serverless             # only use Serverless v1 at this time
      EngineVersion: 13.9                # Django 4.1+ requires PSQL 12+; Serverless v1 only up to 13.9
      DatabaseName:        !Ref DatabaseName
      DBClusterIdentifier: !Ref DatabaseName # default nested stack name is > 63 char PostgreSQL limit
      DBSubnetGroupName:   !Ref DBSubnetGroup
      MasterUsername:      !Ref DatabaseUser
      MasterUserPassword:  !Ref DatabasePassword
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2          # minimum for Serverless v1
        SecondsUntilAutoPause: 300
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  Host:
    Value: !GetAtt Database.Endpoint.Address
  Port:
    Value: !GetAtt Database.Endpoint.Port
  Name:
    Value: !Ref    DatabaseName       # CF has no output for the DatabaseName
  DatabaseUser:
    Value: !Ref    DatabaseUser
  DatabasePassword:
    Value: !Ref    DatabasePassword    
