# https://github.com/aws-samples/aws-apprunner-netcore/blob/main/config/net-core-app-ecr.yaml
## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved
##
### SPDX-License-Identifier: MIT-0

---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create AWS ECR that will have application docker image
Parameters:
  BaseName:
    Type: String

Resources:
  ECRRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${BaseName}
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole' 
  
Outputs:
  Arn:
    Value: !GetAtt ECRRepository.Arn           # arn:aws:ecr:us-east-1:123456789012:repository/my-repository
  RepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri # 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-repository
