
Resources:
  S3MediaBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      # BucketName generated like: scale0-dev-s3-11vqj0ojwb6rf-s3mediabucket-1vf5f69qujs46
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET]
          AllowedOrigins: ['*']
          ExposedHeaders: [Date]
          MaxAge: '300'
      PublicAccessBlockConfiguration: # needed to set acl=public-read
        BlockPublicAcls: false
      OwnershipControls:        # needed if we want to set acl=public-read
        Rules:
          - ObjectOwnership: ObjectWriter
      # LifecycleConfiguration:
      #   Rules:
      #     - Id: ExpireOldVersions
      #       Status: Enabled
      #       NoncurrentVersionExpirationInDays: 100
      # VersioningConfiguration:
      #   Status: Enabled

Outputs:
  Name:
    Description: Bucket name (with no domain) containing media, documents, static assets
    Value: !Ref S3MediaBucket
